project_id = "lnskrkkyeavoshufhwkm"

[functions.admin-password-reset]
verify_jwt = false

[functions.generate-prota-promes]
verify_jwt = false

[functions.generate-rpp]
verify_jwt = false

[functions.send-absensi-reminder]
verify_jwt = false

[functions.send-tunggakan-reminder]
verify_jwt = false

[functions.generate-kktp]
verify_jwt = false